language: c
os: linux
dist: trusty
sudo: required
compiler: clang
branches:
  only:
    - coverity

before_install:
  - bash .travis-deps-linux.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "Iqj+Zdu6+oIi/ERwJreofwiyQ9zwTqME68AyNX6nNTGmiAq+LQM8XMqoyKdfCpm8Ui9BQs1qGgvEQhY2ZRW+Ko9d5ervr3ZEpbXilEoog1HD4ZgZ/Vt9eldOkA6PWD/xKFNvZvtwxfdpBXAYveycvT76z0FKBuq9lAFo032QvY5bhbjQR5sN2sP80fIyQHGls9sOpuElMAgP4h5Oys83PkOD+kqG6UVn7zW2xi8AwWhFlFUXMdusXzsTTwbbqG6aV+7BQC74GyJsKUz3Zk+g0mMerNqs7ihzkKC3QHRsDRjg+X4E5EchQtsTsbw9+pu13cALj+PFNixOg4r9MMf0LXNohMWvBw59Lg9ppF8E6VKoMF5Rqz6kPgyIPbZGPxVIuEvdP+V8k5qYYQM70cM/11hx3k0x7EDQ1b68FgnYdZjhh1oBGQJZGvBWMc0hS3uJ7eEZeSbcvpxMLze7+XapAVDZE3lXOveeAFe+KRCSvjGcpMhDzXPZGZhJSFmLYZ+tMgPAPSvHfHmVotNESr8NoEdr6kURPJKviQTUF/ZoXAMcOhezDm/Xn478atZ8B+VSyLRdSUuuHvT98USgGTaAttmfPxxncmVEkdJW6bYICZKXADKKrPHes7joREWXKvgbOe8n5glGKoWR2xz1EXCtkCQi9jdtYHfPl9Ll+RK3yGM="

addons:
  coverity_scan:
    project:
      name: "CESNET/libnetconf2"
    notification_email: rkrejci@cesnet.cz
    build_command_prepend: "mkdir build ; cd build ; cmake -DENABLE_TLS=ON -DENABLE_SSH=ON .. "
    build_command: "make"
    branch_pattern: coverity

script:
  # do nothing, everything here is done in coverity addon
  - true
